name: Actions-Practise

on: push

jobs:
  test:
    name: Working on Actions
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Download NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Latest LTS Node.js version in 2025

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
