name : Practise
on : workflow_dispatch
jobs:
  firstjob: 
    name: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name : Hello
        run : echo "Hello Murali"
      - name : Sample
        run : echo "Sample Done" 
