name : First Github Action
on : workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name : Greetings
    run : echo "Hello Murali"
    - name : Gathering-Details
    run : read -p "Enter Your Name: " A
    run : read -sp "Enter Your Password: " B
    run : echo "The Name is ${A} and the password is ${B}"
    
