name : Github-Test
on : workflow-dispatch
jobs:
  first-job: Practise
    runs on: ubuntu-latest
    steps:
      - name : Greeting
        run : echo "Hello"
      - name: Bad
        run : echo "Coming"
