name : First File
on : workflow_dispatch
jobs:
  firstjob:
    name: First-Job
    runs-on: ubuntu-latest
    steps:
      - name : Greet
        run : echo "Hello"
      - name : done
        run : echo "Sample DOne"
      - name : Testing Shell
        run: |
            echo "First output"
            echo "Second output"
      - name: Outputs
        run: echo "${{ toJSON(github) }}"
