name : Practise
on : workflow-description
jobs:
  firstjob: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name : Hello
        run : "Hello Murali"
      - name : Sample
        run : "Sample Done" 
