name : First WorkFlow
on : workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Greeting
      run: echo "Hello World"
      run : read -p "Enter Your Name: " A
      run : read -sp "Enter Your Password: " B
      run : echo "The Name is ${A} and the password is ${B}"

    - name: Exiting Greeting
      run: echo "Hello World Bye"
    
  

    
