name : Ok
on : workflow_dispatch
jobs:
  firstjob:
    name: First-Job
    runs-on: ubuntu-latest
    steps:
      - name : Greet
        run : echo "Hello"
      - name : done
        run : echo "Sample DOne"
