name : Practise
on : workflow_dispatch
jobs:
  firstjob: 
    name: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name : Hello
        run : "Hello Murali"
      - name : Sample
        run : "Sample Done" 
