name : MultipleJOBS
on : push
jobs:
  firstjob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name : Testing
        run : echo "Hello This is a Testing JOB"
      - name : done
        run : echo "Sample Testing Success"
  secondjob:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name : Development
        run : echo "Hello This is Dev Stage"
      - name : Deploy-Done
        run : echo "Deployment Success"
      - name : Testing Shell
        run: |
            echo "First output"
            echo "Second output"
