name: Multiple-Jobs-One-After-another
on: push
jobs:
  firstjob:
      name: Testing
      runs-on: ubuntu-latest
      steps:
      - name : Testing Phase
        run : |
         echo "Hello This is a Testing Phase"
         echo "Development Stage will be done only once this Testing Phase Success"
  Dev:
    needs: firstjob
    name: Devlopment
    runs-on: ubuntu-latest
    steps:
      - name : Development
        run : echo "Tesing Done, So Development is success"
